/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import Controller.ProjectController;
import Controller.TaskController;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;

public class App {
   

    public static void main(String[] args) {
        
       
        
       
        
        
       
        
        
    }
}
